Define our goals.
hober/web-extensions pull request #11
Opened 2020-10-05 17:55 UTC by hober

2020-10-05 18:00 UTC, hober commented
Reviews very welcome, @kewisch @jessieberlin @dotproto @cwilso @tantek @MaheshKumarJha!

2020-10-06 01:14 UTC, tantek requested changes
These goals are a good summary. One nit, since it looks like this is the first time the seemingly generic phrase "web extensions" is used in the document, it may benefit from a more precise description, noting that the rest of the doc will use "web extensions" as that shorthand.

E.g.

s/core of APIs for web extensions./core of APIs for web browser extensions (hereafter summarily referred to as "web extensions").

Feel free to wordsmith. I think by making it clear at the start that we're talking about web *browser* extensions, and not some generic model of extensions for all web technologies (like a couple of TLAs that shall not be named), it'll help reduce confusion when read by a broader audience.

2020-10-06 11:45 UTC, kewisch commented on charter.md
> +extensions. By specifying the APIs, functionality, and permissions of
```suggestion
We will specify a model, permissions, and a common core of APIs for WebExtensions. By specifying the APIs, functionality, and permissions of
```

2020-10-06 11:47 UTC, kewisch commented
I like Tantek's suggestion and as mentioned in another PR would like us to use WebExtensions instead of web extensions.

2020-10-06 11:47 UTC, kewisch approved these changes

2020-10-07 18:29 UTC, hober commented
@tantek @kewisch okay, I think I've fixed this in e7fe561. Please take another look.

2020-10-08 00:34 UTC, tantek approved these changes
LGTM

2020-10-08 21:03 UTC, merged

2020-10-09 18:47 UTC, kewisch commented
LGTM!