Add the Maintainability design principle.
hober/web-extensions pull request #19
Opened 2020-10-08 21:25 UTC by hober

Splitting #3 up into one PR per principle, so we can quickly land the uncontroversial ones, and have focused discussion on the others. PTAL, @dotproto, @kewisch, @MaheshKumarJha.

2020-10-09 18:55 UTC, kewisch approved these changes

2020-10-13 04:20 UTC, dotproto requested changes

2020-10-13 04:20 UTC, dotproto commented on charter.md
> +APIs extensions must adopt to a minimum, and will only add such APIs
```suggestion
APIs extensions must adopt to a minimum, and will only revise such APIs
```

Small tweak to expand the scope to include changes and removals. I opted for "revise" here In order to abstractify the specific nature of the change to the API surface, but other options that leap to mind include "change", "modify", and "update".

2020-10-13 15:16 UTC, dotproto commented
After writing [this comment](https://github.com/hober/web-extensions/pull/14#issuecomment-707495631) on #14 yesterday and re-reading this principal several times, it occurred to me I realized that I'm not sure what group of developers the current language targets: extension authors or user-agent implementers. 

I originally interpreted "enable the widest group of developers to write and maintain extensions" and "to keep the maintenance cost of extensions as low as we can" as trying to minimize the maintenance cost for authors creating browser extensions, but the inclusion of the Avoid Needless Complexity principal's note that "Simpler features are easier for user agents to implement" muddied that interpretation.

2020-10-26 17:46 UTC, jessieberlin commented
> After writing [this comment](https://github.com/hober/web-extensions/pull/14#issuecomment-707495631) on #14 yesterday and re-reading this principal several times, I realized that I'm not sure what group of developers the current language targets: extension authors or user-agent implementers.
> 
> I originally interpreted "enable the widest group of developers to write and maintain extensions" and "to keep the maintenance cost of extensions as low as we can" as trying to minimize the maintenance cost for authors creating browser extensions, but the inclusion of the Avoid Needless Complexity principal's note that "Simpler features are easier for user agents to implement" muddied that interpretation.

Why can't it target both?

2020-10-29 15:10 UTC, jessieberlin commented
What about "to keep the maintenance cost of extensions as low as we can" becoming ""to keep the maintenance cost of extensions as low as we can for browser vendors and extension developers"?

2020-10-29 16:05 UTC, hober commented
Okay, I just pushed the change we agreed to on the call. Is this ready to merge, @dotproto @kewisch @MaheshKumarJha?

2020-11-02 19:43 UTC, jessieberlin commented on charter.md
> +extensions **must** adopt to a minimum, and will only revise such APIs
No, we explicitly want to minimize the number of APIs that WebExtension developers must adopt in order to make a WebExtension. Adopt is exactly what is meant here.

2020-11-02 20:43 UTC, Rob--W commented on charter.md
> +extensions **must** adopt to a minimum, and will only revise such APIs
So, just to make sure that I've understood you well: this sentence is just emphasizing that the previously stated "simplicity" is meant to explicitly cover the desire to avoid unnecessary boilerplate? Looks sensible.

If my understanding is correct, consider this thread resolved.

Otherwise, could you give an example/ counter-example?

2020-11-03 03:14 UTC, jessieberlin commented on charter.md
> +extensions **must** adopt to a minimum, and will only revise such APIs
Yes, your understanding is correct!

2020-11-03 11:28 UTC, Rob--W approved these changes

2020-11-05 03:15 UTC, dotproto approved these changes
LGTM 👍

2020-11-05 03:15 UTC, dotproto commented on charter.md
> +extensions **must** adopt to a minimum, and will only revise such APIs
Stylistic nit: I think this is the only place where we decorate a word for emphasis. I think it would carry the same weight and be more consistent if we dropped the bold on "must", but this is not a blocking concern.

2020-11-09 13:00 UTC, mpurohit7 approved these changes

2020-11-09 18:32 UTC, merged