Add the Quality design principle.
hober/web-extensions pull request #20
Opened 2020-10-08 21:26 UTC by hober

Splitting #3 up into one PR per principle, so we can quickly land the uncontroversial ones, and have focused discussion on the others. PTAL, @dotproto, @kewisch, @MaheshKumarJha.

2020-10-09 19:03 UTC, kewisch commented on charter.md
> +browser developers to best achieve interoperability. [[Well-defined
Just double checking on this one. The headline is quality, but then interoperability is mentioned as a main theme. Would it be better to mention how we'd like to ensure that the APIs allow extension developers to write good quality code, and maybe a similar aspect about browser vendors? Or do we change the headline to interoperability?

2020-10-13 04:07 UTC, dotproto requested changes

2020-10-13 04:07 UTC, dotproto commented on charter.md
> +browser developers to best achieve interoperability. [[Well-defined
I'd agree that this feels like a conflation. As I see it a thoroughly defined behavior is an aspect of API or specification's quality, but is only one part of the broader story.

The linked principal states

> Prefer to clearly define behavior that content authors could rely on, in preference to vague or implementation-defined behavior. This way, it is easier to author content that works in a variety of user agents. However, implementations should still be free to make improvements in areas such as user interface and quality of rendering.

Given the current copy and the linked design principal, it may be best to rename this section to better match it's contents. How about changing the section title to "Well Defined Behavior"?

2020-10-29 15:45 UTC, hober commented
I just pushed a change that renames the principle to Well-defined Behavior.

2020-10-29 15:47 UTC, kewisch commented on charter.md
> +browser developers to best achieve interoperability. [[Well-defined
This looks good to me!

2020-10-29 15:48 UTC, kewisch approved these changes

2020-10-29 15:56 UTC, merged