Define our goals and principles.
hober/web-extensions pull request #3
Opened 2020-08-14 18:17 UTC by hober

2020-08-25 23:43 UTC, hober commented
> The use of "standard" & "standardize" are problematic[...]

I think I fixed all of them in 8c29c3b. Please take another look and let me know if I missed anything.

2020-08-26 11:58 UTC, kewisch approved these changes
From my end this PR looks good and covers the goals we've previously discussed. Thanks!

2020-08-28 17:49 UTC, hober commented
> LGTM with one minor editorial nit:
> s/to to/to/g
> (two occurrences)

Fixed in 90276cd.

2020-08-28 23:55 UTC, hober commented
@dotproto @cwilso could one of you take a look?

2020-08-29 00:10 UTC, cwilso commented on charter.md
> +We will standardize a model, permissions, and a common core of APIs for
"standardize" is problematic in a CG.  I think we should use the verb "incubate".

2020-08-29 00:10 UTC, cwilso commented on charter.md
> +web extensions. By standardizing the APIs, functionality, and
Similarly:  "By incubating a common model for the APIs, functionality, ..."

2020-08-29 02:08 UTC, tantek commented on charter.md
> +We will standardize a model, permissions, and a common core of APIs for
Can you recheck the full latest diff? I gave the same feedback and then @hober addressed it in a subsequent edit.

2020-08-29 02:08 UTC, tantek commented on charter.md
> +web extensions. By standardizing the APIs, functionality, and
same

2020-09-11 05:44 UTC, dotproto requested changes

2020-09-11 05:44 UTC, dotproto commented on charter.md
> +
```suggestion

### Autonomy

Individual browser vendors have the freedom to choose they course believe is
best for their end users and developers. Our processes embrace this and seek to
provide mechanisms for specifying inconsistencies and working towards eventual
unification where appropriate. We also recognize that not all APIs or
capabilities need to be specified.

```

This is the closest thing I could think of to a PR for a PR. This suggestion aims to address an area of discussion from our last sync.

2020-09-13 23:40 UTC, jessieberlin commented on charter.md
> +developers and implementers. [[Priority of
What is the distinction between  "authors" and "implementers" here?

2020-09-13 23:49 UTC, jessieberlin commented on charter.md
> +Users](https://intarchboard.github.io/for-the-users/draft-iab-for-the-users.html)]
I like this suggestion.

2020-09-13 23:51 UTC, jessieberlin commented on charter.md
> +Content](https://www.w3.org/TR/html-design-principles/#support-existing-content)]
I think we need to discuss this in more depth. A huge part of the benefits here is giving extension developers the confidence that they won't need to keep throwing out and rewriting.

2020-09-13 23:52 UTC, jessieberlin commented on charter.md
> +Wheel](https://www.w3.org/TR/html-design-principles/#do-not-reinvent-the-wheel)]
I think this relies on resolution of the previous comment :)

2020-09-13 23:52 UTC, jessieberlin commented on charter.md
> +[[Security and privacy are
👍

2020-09-13 23:52 UTC, jessieberlin commented on charter.md
> +extensions on a variety of devices and operating systems [[The web is
👍

2020-09-13 23:53 UTC, jessieberlin commented on charter.md
> +
I think this relies on resolution of the previous comment :)

2020-09-13 23:56 UTC, jessieberlin commented on charter.md
> +
I think if we added something like this, we would want to include something stating that the core model, permissions, etc is expected to be the same.

2020-09-14 01:42 UTC, dotproto commented on charter.md
> +developers and implementers. [[Priority of
For the sake of discussion, Section 3.2 of the HTML Design Principals states

> 3.2. Priority of Constituencies
> 
> In case of conflict, consider users over authors over implementors over specifiers over theoretical purity. In other words costs or difficulties to the user should be given more weight than costs to authors; which in turn should be given more weight than costs to implementors; which should be given more weight than costs to authors of the spec itself, which should be given more weight than those proposing changes for theoretical reasons alone. Of course, it is preferred to make things better for multiple constituencies at once.

I believe the distinction they're drawing is that spec authors may not be the same as spec implements. At the moment we only have browsers engaging in this discussion, but it's possible that a prolific extension author or another 3rd party might become a specification author. I mostly read this as saying that the browser engineers implementing a specification don't get to overrule the editors because the spec would require more work or layers of indirection than they'd otherwise be inclined to implement.

2020-09-14 01:42 UTC, dotproto commented on charter.md
> +Content](https://www.w3.org/TR/html-design-principles/#support-existing-content)]
Yeah, this seems like something that may be easier to get to the heart of through conversation. To be clear, I agree that consistency is an important aspect of any platform people target and I'm not against declaring it as a goal.

Rather, I think my hesitation is rooted in the fact that there is a balance to strike between consistency and platform evolution and the current PR text only weighs in on one side of the scales. Perhaps we should leave this section as is and introduce another goal that focuses on how we approach breaking changes.

2020-09-14 01:42 UTC, dotproto commented on charter.md
> +Wheel](https://www.w3.org/TR/html-design-principles/#do-not-reinvent-the-wheel)]
Why does this line rely on resolution of the previous comment? To my eye this line explicitly targets cross-browser compatibility (portability) rather than compatibility with different versions a well-specified browser extension platform (the previous line in the PR).

2020-09-14 15:27 UTC, jensimmons commented on charter.md
> +developers and implementers. [[Priority of
In Section 3.2 of the HTML Design Principals, "Authors" refers to developers (& designers & more) — people making websites or extensions. "Implementors" means people making browsers. "Specifiers" means people writing specifications and web standards. These terms are used frequently in this way inside working groups.

2020-09-14 17:05 UTC, tantek commented on charter.md
> +We will standardize a model, permissions, and a common core of APIs for
@cwilso can you recheck the one changed file? https://github.com/hober/web-extensions/pull/3/files At this point I'd like to see these improvements merged (dropping "standard[ize]"), and then further pull requests to address all the other changes that are being discussed some of which seem beyond the scope of this edit. Or perhaps there's a need to start over with a new pull request anyway since I now see that "This branch has conflicts that must be resolved". Up to you @hober, ok either way.

2020-09-14 19:03 UTC, tantek commented on charter.md
> +Content](https://www.w3.org/TR/html-design-principles/#support-existing-content)]
@jessieberlin wrote:
> I think we need to discuss this in more depth

Agreed. This sounds like it is worth its own issue, rather than debating in part of a specific pull request.

2020-09-16 04:04 UTC, dotproto commented on charter.md
> +developers and implementers. [[Priority of
Thanks for the correction, Jen!

2020-09-21 21:46 UTC, dotproto commented on charter.md
> +
Just opened PR #9 to discuss this idea.

@hober, I don't see a way to resolve this comment thread on my end. Can you?

2020-09-29 17:23 UTC, dotproto commented on charter.md
> +We will standardize a model, permissions, and a common core of APIs for
@cwilso The latest text uses "specify" rather than "standardize". Does this address your concerns, or do you have a strong preference for incubate? If the latter, could you explain?

2020-09-29 19:37 UTC, cwilso commented on charter.md
> +We will standardize a model, permissions, and a common core of APIs for
I do have a preference for "incubate", but don't have a blocking objection to "specify".  It should, however, be clear that any output of this group (as a CG) doesn't have any more weight in terms of W3C formal weight than any other incubation output of a CG.

2020-09-29 20:49 UTC, hober commented on charter.md
> +
I don't think Do Not Reinvent The Wheel applies to Portability. It applies to Compatibility.

2020-09-29 20:55 UTC, hober commented on charter.md
> +Content](https://www.w3.org/TR/html-design-principles/#support-existing-content)]
I want to say that we made progress on this during our last call, but I don't remember any of the details. Did we come to a shared understanding here?

2020-10-05 17:55 UTC, hober commented
I'm going to split this up into separate PRs per design principle, per our lat call.

2020-10-05 17:55 UTC, closed without merging