Declare browser autonomy as an explicit goal
hober/web-extensions pull request #9
Opened 2020-09-21 21:27 UTC by dotproto

This pull request introduces an "Autonomy" heading in the Goals section. This idea was originally introduced in [a comment](https://github.com/hober/web-extensions/pull/3#discussion_r486785841) on PR #3 and was broken into a separate PR for the sake of more focused discussion.

2020-09-22 18:52 UTC, jessieberlin commented on charter.md
> +APIs for web extensions that all browsers can build upon.
I think "that all browsers can build upon" needs to be a little stronger, especially to balance out the first sentence of  "Individual browser vendors are free to implement browser extensions in  whatever way they feel is best".

2020-09-25 17:32 UTC, dotproto commented on charter.md
> +APIs for web extensions that all browsers can build upon.
Please consider everything I've written so far to be draft language. I'm not beholden to any particular wording I've used here. 

One of the issues I was grappling with as I was drafting this is that it's not clear to me how much a specification or standard can demand of a browser vendor. This may be ignorance on my part, but I'm not aware of any formal commitment that browsers make to implementing any given spec or standard. I chose the phrase "that all browsers can build upon" because of a mix of that concern and the previously discussed desire for us to start with a small core of APIs, systems, and concepts that we specify as web extensions.

I still don't have a good idea on how we could better frame this, but I'm totally open to suggestion. Do you have any opinions on how we could strengthen this wording or rewrite it?

2020-10-06 12:07 UTC, kewisch commented on charter.md
> +APIs for web extensions that all browsers can build upon.
Maybe start with something like "We recognize that browser vendors are in need of a mechanism to experiment with new features and provide functionality that is specific to the respective browser. Our processes embrace this...."

At least in the specification phase I don't feel there would be any formal commitment to make changes in accordance to what is specified. This is slightly more the case if we eventually standardize. But even then, a browser vendor may choose to disregard the standard. It would mainly be a matter of public perception as to what that means in the long run.

2020-10-06 12:13 UTC, kewisch commented on charter.md
> +
I think what I would like to see in this section is a commitment that browser vendors are open to making changes to already shipped features if the spec/standard we agree on would require it. While this may have an additional impact on the vendor to migrate developers, not doing so puts pressure on the other vendors to accept status quo because there is already a shipped implementation. I'm hoping that through the spec and future standard, we can bring the best possible extension model and APIs to developers together.

2020-10-06 12:14 UTC, kewisch requested changes

2020-10-06 12:14 UTC, kewisch commented on charter.md
> +
I think what I would like to see in this section is a commitment that browser vendors are open to making changes to already shipped features if the spec/standard we agree on would require it. While this may have an additional impact on the vendor to migrate developers, not doing so puts pressure on the other vendors to accept status quo because there is already a shipped implementation. I'm hoping that through the spec and future standard, we can bring the best possible extension model and APIs to developers together.

2020-10-15 14:29 UTC, zombie commented on charter.md
> +APIs for web extensions that all browsers can build upon.
I'm questioning the need to specifically call out "Browser vendors can do what they want".  I'm not familiar with a similar "Autonomy" principle for other web-related standards, and yet there's a perception that Google (Chrome) already behaves in a similar way (for example, see [quotes](https://twitter.com/anssik/status/1313862250868940801) from the recent "Investigation of Competition in Digital Markets" by a Committee of the U.S Congress).

2020-10-15 17:32 UTC, dotproto commented
At the end of our sync @rob--w raised the following concern.

> Previous wording was: “We also recognize that not all APIs or capabilities need to be specified”
> New wording is: “Given this, we expect browser vendors to support APIs and capabilities that we do not specify.”
> Perspective changed from “expectations for the spec” to “(obvious) expectations for the browser”.

2020-10-15 18:25 UTC, kewisch approved these changes
The changed text looks great to me, thanks for pushing through this!

2020-10-29 02:58 UTC, dotproto commented on charter.md
> +do not specify.
```suggestion
Given this, we expect browsers will support APIs and capabilities that we do not
specify and may iterate on specified APIs.
```

While reviewing this PR earlier today, one of our extensions engineers called out that the current framing does not address potential divergences between specified behavior and a browser's implementation. This suggestion attempts to address that gap.

2020-10-29 15:34 UTC, Rob--W commented on charter.md
> +do not specify.
```suggestion
Given this, we expect browser vendors to offer APIs and capabilities beyond what's specified.
```

(changed wording to capture the original meaning plus the desire to emphasize that vendors may iterate on existing APIs.)

2020-10-29 20:52 UTC, dotproto commented on charter.md
> +do not specify.
In today's sync the concerns were raised that this suggestion stands in direct contrast to the goal of providing developers with a consistent, stable, cross-browser platform. Given these concerns, I'm dropping this suggestion.

2020-11-05 03:09 UTC, dotproto commented
At this point I think all parties are comfortable with the current language for this goal.

2020-11-10 15:40 UTC, mpurohit7 approved these changes

2020-11-10 16:43 UTC, merged